name: PythonAI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v1.0.0'  # Only publish on version tags like v1.0.0
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest tests/

    - name: Build package
      run: |
        pip install build
        python -m build

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        pip install twine
        twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}